### ISSUE TITLE
是否需要另开一个“插件”主题，以便提供插件文档

### ISSUE THREAD

**Issue by dragon-fish** [Wjghj-Project/InPageEdit-Document#18]
> 要不同步更新一下文档，简单讲一下怎么配置 cm6？
> 
> https://github.com/inpageedit/Documentation/blob/b4f753f5a8d2dd4760dd2b7f0df5e25265c62056/src/guide/usage/preference.md?plain=1#L39

也可以另开一个“插件”主题，把 CodeMirror 的文档移进去

_Originally posted by @dragon-fish in https://github.com/inpageedit/Plugins/issues/50#issuecomment-1955791998_

**Comment by bhsd-harry** [comment]
好的，我晚点把 Wikiplus-highlight 的文档复制一份过来。

**Comment by bhsd-harry** [comment]
我看了下文档，CM6的设置与IPE的其他设置不同，不是通过修改JS对象实现的，而是通过对话框的UI进行勾选。
